name: PraxisClient
version: 0.0.1
author: Samuel Richardson
description: Praxis game client
homepage: http://www.richardson.co.nz
dependencies:
  browser: any
  dartemis: 0.6.0
  logging: 0.9.2
  pixi: 0.1.2
